### ISSUE TITLE
Can you please upload the pretrained model?

### ISSUE THREAD

**Issue by ghost** [WiraDKP/pytorch_speaker_embedding_for_diarization#1]
Thank you!

**Comment by WiraDKP** [comment]
Sure, I have uploaded a pretrained model both in pytorch and OpenVINO.
Hope it helps. Thanks. 

61da1b7fe61111355f9329c7c0db20b2ecd0a411

**Comment by shobhitu** [comment]
> I have uploaded a pretrained model b

I tried to do the prediction using ur models but getting the following error:
RuntimeError: Error(s) in loading state_dict for Encoder:
	Missing key(s) in state_dict: "conv.18.weight", "conv.19.weight", "conv.19.bias", "conv.19.running_mean", "conv.19.running_var", "conv.21.weight", "conv.22.weight", "conv.22.bias", "conv.22.running_mean", "conv.22.running_var", "conv.24.weight", "conv.25.weight", "conv.25.bias", "conv.25.running_mean", "conv.25.running_var", "conv.27.weight", "conv.28.weight", "conv.28.bias", "conv.28.running_mean", "conv.28.running_var". 
	size mismatch for conv.9.weight: copying a param with shape torch.Size([256, 256, 1, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 1, 5]).
	size mismatch for conv.12.weight: copying a param with shape torch.Size([256, 256, 1, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 1, 5]).
